---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: flagger
  namespace: flagger
spec:
  interval: 120m
  url: https://flagger.app
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flagger
  namespace: flagger
spec:
  interval: 30m
  chart:
    spec:
      chart: flagger
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: flagger
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    meshProvider: gatewayapi:v1
    metricsServer: http://prometheus-operated.monitoring:9090/prometheus/
